app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shoebox/', include('shoebox.urls')),
    path('user/', include('user.urls'))
]

shoebox/urls.py
from django.urls import path
from . import views

app_name = 'shoebox'

urlpatterns = [
    
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    # user/

    # 회원가입
    path('register/', views.Registration.as_view(), name='register'),
    # 로그인
    path('login/', views.Login.as_view(), name='login'),
    # 로그아웃
    path('logout/', views.Logout.as_view(), name='logout'),
]

shoebox/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils import timezone

'''
Django 자체에서 UserManager는 유저 생성을 도와주는 매니저 클래스입니다.
이 클래스에서는 create_user(), create_superuser() 두 메서드가 제공되는데
수업에서는 이를 우리가 수정한 User 모델에 맞춰 변경해주었습니다.
_create_user()는 필수 필드를 검증한 다음
create_user(), create_superuser()로 구분해서 사용자와 관리자를 생성할 수 있습니다.
'''
class UserManager(BaseUserManager):
    
    def _create_user(self, userId, password, is_staff, is_superuser, **extra_fields):
    # User모델의 username이 아니라 email을 id처럼 사용하기 위해서 email이 필수임을 체크합니다. -> 아닐시 오류를 발생시켜 유저 생성이 진행되지 않습니다.
        if not userId:
            raise ValueError('User must have an userId')
        # now = timezone.now() # 현재시간 -> UTC
        now = timezone.localtime() # User 테이블에 타입(class User(AbstractUser) 내부의 last_login, date_joined 필드)에 맞춰 현재 시각을 가져오기 위한 부분입니다. (데이터 타입: datetime)
        # email = self.normalize_email(email)
# normalize_email은 BaseUserManager에서 제공하는 메서드로 정규화를 실행하는 메서드(함수)입니다.
# 이메일 주소의 대소문자 구분에 따른 중복계정 방지를 위해 사용됩니다.
        user = self.model(
            userId=userId,
            is_staff=is_staff,
            is_active=True,
            is_superuser=is_superuser,
            last_login=now,
            date_joined=now,
            **extra_fields
        ) # 일반 유저인지 관리자 유저인지를 메서드 실행시 입력받은 값으로 구분해서 유저를 생성합니다.
        user.set_password(password) # 여기서 set_password 메서드는 사용자에게 받은 암호를 안전하게 저장하기 위해 암호화 과정을 더해주는 부분입니다.
        user.save(using=self._db) # using는 어떤 데이터베이스를 사용할 지 지정해주는 매개변수로 self._db는 현재 사용중인 데이터베이스를 의미합니다.
        return user
    # create_user
    def create_user(self, userId, password, **extra_fields):
        return self._create_user(userId, password, False, False, **extra_fields)
    # create_superuser
    def create_superuser(self, userId, password, **extra_fields):
        return self._create_user(userId, password, True, True, **extra_fields)

# Create your models here.
class User(AbstractUser):
    username = None
    userId = models.CharField(unique=True, max_length=20) # email 값이 기본키가 된다
    name = models.CharField(max_length=50, null=True, blank=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    # password = models.CharField(max_length=50)
    # registered_date = models.DateTimeField(auto_now_add=True)
    # auto_now_add 는 처음 한번 생성했을 때(수정이 필요 없을 때)
    # auto_now 는 업데이트 할 때마다(수정이 필요할 때)

    USERNAME_FIELD = 'userId'
    # EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = [] # superuser 만들때 필요

    objects = UserManager()

    # def __str__(self):
    #     return self.name

user/forms.py
# from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
# from .models import User
from django.contrib.auth import get_user_model

User = get_user_model()

class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['userId'] # 입력받을 항목
        # fields = UserCreationForm.Meta.fields + ('email', )


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['userId', 'password']
        # widgets = {
        #     'email': forms.EmailInput(attrs={'placeholder': 'email'}),
        #     'password': forms.PasswordInput(attrs={'placeholder': 'password'}),
        # }

shoebox/views.py
from django.shortcuts import render

# Create your views here.
class Index

user/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.contrib.auth import authenticate, login, logout
# from .models import User
from .forms import LoginForm, RegisterForm

# Create your views here.


### Registration
class Registration(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('blog:list')
        # 회원가입 페이지
        # 정보를 입력할 폼을 보여주어야 한다.
        form = RegisterForm()
        context = {
            'form': form,
            'title': 'User',
            'type' : 'register'
        }
        return render(request, 'user/user_register.html', context)

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():

            user = form.save()
            # 로그인 한 다음 이동해도 됨, 일단은 아래0로 리다이렉트하게 해놈.
            return redirect('user:login')
        

### Login
class Login(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('blog:list')
        
        form = LoginForm()
        context = {
            'form': form,
            'title': 'User',
            'type' : 'login'
        }
        return render(request, 'user/user_login.html', context)
        
    def post(self, request):
        if request.user.is_authenticated:
            return redirect('blog:list')
        
        form = LoginForm(request, request.POST)
        if form.is_valid():
            userId = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(userId=userId, password=password) # True, False
            
            if user:
                login(request, user)
                return redirect('blog:list')
            
            form.add_error(None, '아이디가 없습니다.')
        
        context = {
            'form': form
        }
        
        return render(request, 'user/user_login.html', context)
### Logout
class Logout(View):
    def get(self, request):
        logout(request)
        return redirect('/')

templates/base.html
<!DOCTYPE html>
<html lang="ko-KR">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static 'css/post_detail.css' %}"> -->

    <title>
        {% block title %}
            {{ title }}
        {% endblock %}
    </title>
    <style>
        .header {
            display: flex;
            justify-content: space-between;
            margin: 2%;
            align-items: center;
        }

        .login-cont, .regi-cont {
            padding-top: 5%;
            padding-left: 5%;
        }

        .write-form {
            display: flex;
            flex-direction: row-reverse;
        }
        
        .profile-img {
            width: 50px;
            /* height: 30px; */
        }

        /* profile dropdown */
        .header-container{
            position : relative;
            display : inline-block;
            width: 100px;
        }

        .header-menu{
            display : none;
            position : absolute;
            z-index : 1; /*다른 요소들보다 앞에 배치*/
        }

        .header-menu a{
            display : block;
            text-decoration: none;
            color: black;
            background-color: white;
            font-size: 12px;
        }

        .header-container:hover .header-menu {
            display: block;
        }


    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Blog</h1>
            {% if user.is_authenticated %}
            <div class="header-container">
                <span><img src='{% static "image/profile.png" %}' alt="profile" class="profile-img"></span>
                <div class="header-menu">
                    <a href="">내 프로필</a>
                    <a href="{% url 'blog:write' %}">글 작성</a>
                    <a href="{% url 'user:logout' %}">로그아웃</a>
                </div>
            </div>
            <!-- <div>
                <span>Welcome, {{ user.userId }}</span>
                <a href="{% url 'user:logout' %}">Logout</a>
            </div> -->
            {% else %}
                {% if type == 'login' %}
                <div>
                    <span>계정이 없으신가요?</span>
                    <a href="{% url 'user:register' %}">Sign up</a>
                </div>
                {% elif type == 'register' %}
                <div>
                    <span>Please, Login</span>
                    <a href="{% url 'user:login' %}">Login</a>
                </div>
                {% endif %}
            {% endif %}
        </div>
            {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="ko-KR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    
    <title>Index</title>

    <style>
        .container{
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
            margin-top: 15%;
            width: 30%;
            height: 300px;
            border: 1px solid black;
            border-radius: 5%;
        }

        .btn-menu{
            display: flex;
            margin: 3%;
        }
        
        .btn {
            margin: 10px;
        }
    </style>
</head>
<body>
    <div class="container border border-success">
        <h1>Blog</h1>
        <div class="btn-menu">
            <a href="{% url 'user:register' %}" class="btn btn-outline-success">회원가입</a>
            <a href="{% url 'user:login' %}" class="btn btn-outline-success">로그인</a>

        </div>
    </div>
    
    
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

</body>
</html>